version: "3.9"

services:
    db:
        image: postgres:17.0-alpine3.20
        container_name: django_db
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        env_file:
            - ./backend/.env

    backend:
        build: ./backend
        container_name: django_backend
        volumes:
            - ./backend:/backend
        ports:
            - "8000:8000"
        env_file:
            - ./backend/.env
        depends_on:
            - db
        environment:
            - DB_HOST=db
            - DB_PORT=5432

volumes:
    postgres_data:
