# Generated by Django 5.1.1 on 2024-09-23 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(14), django.core.validators.RegexValidator(message='Phone number must start with 62', regex='^62\\d{9,11}$')], verbose_name='phone number'),
        ),
    ]
