# Generated by Django 5.1.1 on 2024-10-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('staff', 'staff'), ('supervisor', 'supervisor'), ('manager', 'manager')], default='staff', max_length=20, verbose_name='role'),
        ),
    ]
