# Generated by Django 5.1.1 on 2024-10-06 13:22

import apps.user.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=128, validators=[apps.user.validators.validate_fullname], verbose_name='fullname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, validators=[apps.user.validators.validate_password], verbose_name='password'),
        ),
    ]
